"""Regenerate the committed Marching Cubes lookup-table header.

The table payloads come from scikit-image's BSD-3-Clause licensed
``_marching_cubes_lewiner_luts`` module. The generated header is committed, so
scikit-image remains a development-only dependency.

Run from the repository root::

    python development/mesh/generate_marching_cubes_tables.py
"""

from __future__ import annotations

from pathlib import Path
from textwrap import wrap

import skimage
import skimage.measure._marching_cubes_lewiner_luts as luts


TABLE_NAMES = (
    "CASESCLASSIC", "CASES", "TILING1", "TILING2", "TILING3_1",
    "TILING3_2", "TILING4_1", "TILING4_2", "TILING5", "TILING6_1_1",
    "TILING6_1_2", "TILING6_2", "TILING7_1", "TILING7_2", "TILING7_3",
    "TILING7_4_1", "TILING7_4_2", "TILING8", "TILING9",
    "TILING10_1_1", "TILING10_1_1_", "TILING10_1_2", "TILING10_2",
    "TILING10_2_", "TILING11", "TILING12_1_1", "TILING12_1_1_",
    "TILING12_1_2", "TILING12_2", "TILING12_2_", "TILING13_1",
    "TILING13_1_", "TILING13_2", "TILING13_2_", "TILING13_3",
    "TILING13_3_", "TILING13_4", "TILING13_5_1", "TILING13_5_2",
    "TILING14", "TEST3", "TEST4", "TEST6", "TEST7", "TEST10",
    "TEST12", "TEST13", "SUBCONFIG13",
)


def generate_header() -> str:
    lines = [
        "#pragma once",
        "",
        "// AUTO-GENERATED by development/mesh/generate_marching_cubes_tables.py.",
        "// Lookup tables derived from scikit-image 0.26.0, BSD-3-Clause.",
        "// The original implementation is based on Lewiner et al. (2003).",
        "// See THIRD_PARTY_NOTICES.md for the complete license notice.",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace bioimage_cpp::mesh::detail {",
        "",
        "struct EncodedLut {",
        "    std::array<int, 3> shape;",
        "    int ndim;",
        "    std::string_view data;",
        "};",
        "",
    ]
    for name in TABLE_NAMES:
        shape, payload = getattr(luts, name)
        padded_shape = tuple(shape) + (0,) * (3 - len(shape))
        shape_text = ", ".join(str(value) for value in padded_shape)
        compact_payload = "".join(payload.split())
        lines.append(
            f"inline constexpr EncodedLut k{name}{{{{{shape_text}}}, {len(shape)},"
        )
        chunks = wrap(compact_payload, width=112)
        for chunk in chunks:
            lines.append(f'        "{chunk}"')
        lines.append("};")
        lines.append("")
    lines.append("} // namespace bioimage_cpp::mesh::detail")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if skimage.__version__ != "0.26.0":
        raise RuntimeError(
            "table regeneration is pinned to scikit-image 0.26.0, got "
            f"{skimage.__version__}"
        )
    output = (
        Path(__file__).resolve().parents[2]
        / "include/bioimage_cpp/mesh/detail/mc33_luts.hxx"
    )
    output.write_text(generate_header())
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
